Repository entando/entando-keycloak-plugin, pull requests merged in 2020-11, with the labels that each got.

#31 ENG-1512: Added extra param "csp.header.extraConfig"
  pom.xml
  preview/entando-sample-app-ekp/src/main/conf/systemParams.properties
  preview/entando-sample-app-ekp/src/test/config/conf/systemParams.properties
  src/main/java/org/entando/entando/aps/servlet/security/KeycloakAuthenticationFilter.java
  src/main/java/org/entando/entando/keycloak/adapter/AuthenticationProviderManagerAdapter.java
  src/main/java/org/entando/entando/keycloak/adapter/UserManagerAdapter.java
  src/main/java/org/entando/entando/keycloak/filter/KeycloakFilter.java
  src/main/java/org/entando/entando/keycloak/services/KeycloakAuthenticationProviderManager.java
  src/main/java/org/entando/entando/keycloak/services/KeycloakAuthorizationManager.java
  src/main/java/org/entando/entando/keycloak/services/KeycloakUserManager.java
  src/main/resources/spring/aps/managers/keycloakBaseManagersConfig.xml
  src/test/java/org/entando/entando/keycloak/filter/KeycloakFilterTest.java
  src/test/java/org/entando/entando/keycloak/services/AuthenticationProviderManagerTest.java
  src/test/java/org/entando/entando/keycloak/services/KeycloakAuthorizationManagerTest.java
  src/test/java/org/entando/entando/keycloak/services/UserManagerIT.java
Labels: size/L

#33 ENG-1512: Update BOM and entando-engine version
  pom.xml
Labels: approved, size/XS

#32 ENG-1553: fix keycloak plugin vulnerabilities
  src/main/java/org/entando/entando/keycloak/filter/KeycloakFilter.java
Labels: approved, do-not-merge/work-in-progress, size/XS
